# Generated by Django 5.2 on 2025-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='return_date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='return_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
